---
name: Math-BigRat
author: Tels
version: 0.16
version_from: lib/Math/BigRat.pm
license: perl
distribution_type: module
generated_by: Math-BigRat version 0.16
installdirs: perl
requires:
  Math::BigFloat: 1.52
  Math::BigInt: 1.78
  Test::Simple: 0.47
