# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-BigRat
version:      0.13
version_from: lib/Math/BigRat.pm
installdirs:  perl
requires:
    Math::BigFloat:                1.47
    Math::BigInt:                  1.73
    Test::Simple:                  0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
