--- #YAML:1.0
name: Math-BigRat
version: 0.14
version_from: lib/Math/BigRat.pm
license: perl
distribution_type: module
generated_by: Math-BigRat version 0.14
installdirs: perl
requires:
  Math::BigFloat: 1.48
  Math::BigInt: 1.74
  Test::Simple: 0.47
